name: ArgonOne V5 Active Linear Cooling
version: "1.0.4"
slug: argon_one_v5_temp_linear
description: Actively keeping your ArgonOne V5 cool on a Pi5.
arch:
  - aarch64
auth_api: true
homeassistant_api: true
hassio_role: homeassistant
hassio_api: true
devices:
  - /dev/i2c-13:/dev/i2c-13:rwm
privileged:
  - SYS_RAWIO
url: https://community.home-assistant.io/t/argon-one-active-cooling-addon/262598/
map:
  - config
  - ssl
  - addons
  - backup
  - share
  - media
options:
  Minimum Temperature: 55
  Maximum Temperature: 85
  Temperature Unit: F
  Create Entity: true
schema:
  Minimum Temperature: int(32,200)
  Maximum Temperature: int(32,200)
  Temperature Unit: list(C|F)
  Create Entity: bool
